### ISSUE TITLE
Animate.css 库的基本使用

### ISSUE THREAD

**Issue by RibsLi** [RibsLi/Blog#4]
<a href="https://animate.style/" target="_blank">参考文档</a>

### 安装
  - **使用npm安装** ` npm install animate.css --save `
  - **使用yarn安装** ` yarn add animate.css `
    - **导入到项目中** ` import 'animate.css' `
  - **使用 CDN 直接添加到网页中**

  ```HTML
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  </head>
  ```

### 基本使用
  - **以类的形式添加到元素中**

    ```HTML
    <!-- 每个动画元素都必须带有 animate__animatedanimate 和动画名称 -->
    <h1 class="animate__animated animate__bounce">An animated element</h1>
    ```

    - 也可以直接在元素的 class 属性上添加其他类来修改对应的属性，您可以自定义它们

    ```HTML
    <div class="animate__animated animate__bounce animate__delay-2s animate__faster animate__repeat-2">Example</div>
    ```

    - animate__delay-2s 修改延迟时间，以下为默认延迟时间
    
    ```
    类名	默认延迟时间
    animate__delay-2s	2s
    animate__delay-3s	3s
    animate__delay-4s	4s
    animate__delay-5s	5s
    ```

    ```CSS
    /* All delay classes will take 2x longer to start */
    :root {
      --animate-delay: 2s;
    }
    ```

    - animate__faster 控制动画速度，以下为默认速度

    ```
    类名	默认速度时间
    animate__slow	2s
    animate__slower	3s
    animate__fast	800ms
    animate__faster	500ms
    ```

    ```CSS
    /* All animations will take twice as long to finish */
    :root {
      --animate-duration: 2s;
    }
    ```

    - animate__repeat-2 控制动画的迭代次数

    ```
    类名	默认迭代计数
    animate__repeat-1	1
    animate__repeat-2	2
    animate__repeat-3	3
    animate__infinite	infinite
    ```

    ```CSS
    .my-element {
      --animate-repeat: 2;
    }
    ```

  - **用@keyframes**

    ```CSS
    .my-element {
      animation: bounce; /* referring directly to the animation's @keyframe declaration */
      animation-duration: 2s; /* don't forget to set a duration! */
    }
    ```

  - **CSS 自定义属性（CSS 变量）**
    - 从版本 4 开始，Animate.css 使用自定义属性（也称为 CSS 变量）来定义动画的持续时间、延迟和迭代。这使得 Animate.css非常灵活且可定制。需要更改动画持续时间？只需全局或本地设置新值即可。

    ```CSS
    /* This only changes this particular animation duration */
    .animate__animated.animate__bounce {
      --animate-duration: 2s;
    }

    /* This changes all the animations globally */
    :root {
      --animate-duration: 800ms;
      --animate-delay: 0.9s;
    }
    ```

  - **与 Javascript 一起使用**
    - 给元素增加动画

    ```JavaScript
    const element = document.querySelector('.my-element');
    element.classList.add('animate__animated', 'animate__bounceOutLeft');
    ```

    - 或更改其持续时间

    ```JavaScript
    const element = document.querySelector('.my-element');
    element.style.setProperty('--animate-duration', '0.5s');
    ```

    - 监听动画何时结束

    ```JavaScript
    const element = document.querySelector('.my-element');
    element.classList.add('animate__animated', 'animate__bounceOutLeft');

    element.addEventListener('animationend', () => {
      // do something
    });
    ```

    - 您还可以使用一个简单的函数来添加动画类并自动删除它们

    ```JavaScript
    const animateCSS = (element, animation, prefix = 'animate__') =>
    // We create a Promise and return it
    new Promise((resolve, reject) => {
      const animationName = `${prefix}${animation}`;
      const node = document.querySelector(element);

      node.classList.add(`${prefix}animated`, animationName);

      // When the animation ends, we clean the classes and resolve the Promise
      function handleAnimationEnd(event) {
        event.stopPropagation();
        node.classList.remove(`${prefix}animated`, animationName);
        resolve('Animation ended');
      }

      node.addEventListener('animationend', handleAnimationEnd, {once: true});
    });
    ```

    并像这样使用它

    ```JavaScript
    animateCSS('.my-element', 'bounce');
    // or
    animateCSS('.my-element', 'bounce').then((message) => {
      // Do something after the animation
    });
    ```
