### ISSUE TITLE
vue3.x过渡 & 动画

### ISSUE THREAD

**Issue by RibsLi** [RibsLi/Blog#6]
<a href="https://v3.cn.vuejs.org/guide/transitions-enterleave.html" target="_blank">参考文档</a>

### 单元素/组件的过渡
  - Vue 提供了 transition 的封装组件，在下列情形中，可以给任何元素和组件添加进入/离开过渡

### 在进入/离开的过渡中，会有 6 个 class 切换。

  - v-enter-from：定义进入过渡的开始状态。在元素被插入之前生效，在元素被插入之后的下一帧移除。

  - v-enter-active：定义进入过渡生效时的状态。在整个进入过渡的阶段中应用，在元素被插入之前生效，在过渡/动画完成之后移除。这个类可以被用来定义进入过渡的过程时间，延迟和曲线函数。

  - v-enter-to：定义进入过渡的结束状态。在元素被插入之后下一帧生效 (与此同时 - v-enter-from 被移除)，在过渡/动画完成之后移除。

  - v-leave-from：定义离开过渡的开始状态。在离开过渡被触发时立刻生效，下一帧被移除。

  - v-leave-active：定义离开过渡生效时的状态。在整个离开过渡的阶段中应用，在离开过渡被触发时立刻生效，在过渡/动画完成之后移除。这个类可以被用来定义离开过渡的过程时间，延迟和曲线函数。

  - v-leave-to：离开过渡的结束状态。在离开过渡被触发之后下一帧生效 (与此同时 v-leave-from 被移除)，在过渡/动画完成之后移除。

![3](https://user-images.githubusercontent.com/90769279/165715232-f0dda72b-71a7-4f91-93ae-fb4fd82a0218.png)

这里的每个 class 都将以过渡的名字添加前缀。如果你使用了一个没有名字的 ` <transition> `，则 v- 是这些 class 名的默认前缀。举例来说，如果你使用了 ` <transition name="my-transition"> `，那么 v-enter-from 会替换为 my-transition-enter-from。

### CSS 过渡

  ```HTML
  <transition name="slide-fade">
    <!-- ... -->
  </transition>
  ```

  ```CSS
  /* 可以为进入和离开动画设置不同的持续时间和动画函数 */
  .slide-fade-enter-active {
    transition: all 0.3s ease-out;
  }

  .slide-fade-leave-active {
    transition: all 0.8s cubic-bezier(1, 0.5, 0.8, 1);
  }

  .slide-fade-enter-from,
  .slide-fade-leave-to {
    transform: translateX(20px);
    opacity: 0;
  }
  ```

### CSS 动画

  ```HTML
  <transition name="bounce">
    <!-- ... -->
  </transition>
  ```

  ```CSS
  .bounce-enter-active {
    animation: bounce-in 0.5s;
  }
  .bounce-leave-active {
    animation: bounce-in 0.5s reverse;
  }
  @keyframes bounce-in {
    0% {
      transform: scale(0);
    }
    50% {
      transform: scale(1.25);
    }
    100% {
      transform: scale(1);
    }
  }
  ```

### 自定义过渡 class 类名
可以结合其他第三方css动画库使用，如Animate.css
  - enter-from-class
  - enter-active-class
  - enter-to-class
  - leave-from-class
  - leave-active-class
  - leave-to-class

  ```HTML
  <transition
    name="custom-classes-transition"
    enter-active-class="animate__animated animate__tada"
    leave-active-class="animate__animated animate__bounceOutRight"
  >
    <!-- ... -->
  </transition>
  ```

  ### 自定义动画持续时间

  ```HTML
  <transition :duration="1000">
    <!-- ... -->
  </transition>
  ```

  ```HTML
  <!-- 也可以分别指定进入和离开的持续时间 -->
  <transition :duration="{ enter: 500, leave: 800 }">
    <!-- ... -->
  </transition>
  ```

### JavaScript 钩子

  ```HTML
  <transition
    @before-enter="beforeEnter"
    @enter="enter"
    @after-enter="afterEnter"
    @enter-cancelled="enterCancelled"
    @before-leave="beforeLeave"
    @leave="leave"
    @after-leave="afterLeave"
    @leave-cancelled="leaveCancelled"
    :css="false"
  >
    <!-- :css="false" 会让 Vue 会跳过 CSS 的检测 -->
    <!-- ... -->
  </transition>
  ```

  ```JavaScript
  // 结合 GreenSock 的 JavaScript 过渡使用
  let beforeEnter = (el) => {
    gsap.set(el, {
      scaleX: 0.8,
      scaleY: 1.2
    })
  }
  let enter = (el, done) => {
    gsap.to(el, {
      duration: 1,
      scaleX: 1.5,
      scaleY: 0.7,
      opacity: 1,
      x: 150,
      ease: 'elastic.inOut(2.5, 1)',
      onComplete: done
    })
  }
  let afterEnter = (el) => {}
  let enterCancelled = (el) => {}
  let beforeLeave = (el) => {}
  let leave = (el, done) => {
    gsap.to(el, {
      duration: 0.2,
      delay: 0.5,
      opacity: 0,
      onComplete: done
    })
  }
  let afterLeave = (el) => {}
  // leaveCancelled 只用于 v-show 中
  let leaveCancelled = (el) => {}
  ```

### 过渡模式
- in-out: 新元素先进行进入过渡，完成之后当前元素过渡离开。
- out-in: 当前元素先进行离开过渡，完成之后新元素过渡进入。

```HTML
<transition name="fade" mode="out-in">
  <!-- ... -->
</transition>
```

### 示例：路由切换时给组件增加过渡动画

  ```Pug
  <template lang="pug">
  router-view(v-slot="{ Component }")
    Transition(name="custom-classes-transition" enter-active-class="animate__animated animate__fadeInDown" leave-active-class="animate__animated animate__fadeOutDown" mode="out-in" :duration="500")
      keep-alive
        component( :is="Component")
  </template>
  ```

  - 也可以根据路由导航守卫来设置相应的动画效果

  ```JavaScript
  router.beforeEach((to, from, next) => {
    if(to.meta.index > from.meta.index) {
      // 设置动画
    }
  })
  ```

  - 也可以使用 watch 监听路由的改变来设置动画

  ```JavaScript
  watch(() => route.path, () => {
    // 设置动画
  })
  ```

### 其他过渡效果，请参考文档
  - <a href="https://v3.cn.vuejs.org/guide/transitions-list.html" target="_blank">列表过渡</a> 使用 ` <transition-group> `
  - <a href="https://v3.cn.vuejs.org/guide/transitions-state.html" target="_blank">状态过渡</a>
